language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
matrix:
    allow_failures:
        - julia: nightly
after_success:
    - julia -e 'cd(Pkg.dir("SatelliteToolbox")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
notifications:
    email: false
